#! /bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
python3 /home/narmis/programs/python/pydexcom/dexcom.py &
picom --animations &
nitrogen --set-scaled ~/Pictures/wallpapers/minimalist-planets.jpg
pgrep -x tint2 > /dev/null || tint2 &
#xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2)

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# window decorations
bspc config border_width         4
bspc config window_gap          12
bspc config normal_border_color "#7ccdfd"
bspc config active_border_color "#7ccdfd"
bspc config focused_border_color "#f5748c"
bspc config presel-feedback_colour "#fc9d63"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a GalaxyBudsClient state=floating

bspc rule -a tint2 layer=below
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a scpad sticky=on state=floating rectangle=800x400+250+250
